### ISSUE TITLE
[Kevin] Create proficiency view page

### ISSUE THREAD

**Issue by Rosengren** [Rosengren/CompetencyTracker#17]
Implement the proficiency view and the proficiency posts

**Comment by aizon2456** [comment]
Proficiency is handled by #21 . Proficiency was handled such that permission level affects appearance, and routes were changed to make more realistic appearances.

**Comment by aizon2456** [comment]
Fix in next push will remove the user_id:integer field in the Proficiency table, as there is a join table specifically to handle interactions between the user and proficiencies.

**Comment by aizon2456** [comment]
Fixed by #31
